### ISSUE TITLE
406 Not Acceptable

### ISSUE THREAD

**Issue by davidcittadini** [priomsrb/vimswitch#2]
When I run vimswitch it generates the error "Error: Error when accessing //github.com/??/vimswitch/archive/master.zip: 406 Not Acceptable".  Is that caused by a local configuration issue or is that something to do with vimswitch?  Thanks.

**Comment by priomsrb** [comment]
It looks like vimswitch is trying to download `https://github.com/??/vimswitch/archive/master.zip`. Try see if you can download this file from your browser. Also, are you downloading from a public or private repository?

**Comment by davidcittadini** [comment]
Firstly, vimswitch has not loaded anything into the github repository so there is not a master.zip file to download..  I am trying to upload and restore from a private repository so I have a feeling that vimswitch is not handling authentication to/from the repository properly..  Hope that helps :)

**Comment by priomsrb** [comment]
Ah I see. At the moment vimswitch is not able to upload onto github. You have to do this manually. Once you've pushed your vim settings onto github, vimswitch is able to download it.

**Comment by davidcittadini** [comment]
Thanks, an upgrade for the future :)
